# Generated by Django 2.2.7 on 2020-06-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_passwordreset', '0003_allow_blank_and_null_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
