# Generated by Django 2.2.7 on 2020-06-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_passwordreset', '0004_auto_20200607_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
